// Mock data — no backend, static content only (per challenge requirements)

const RESTAURANTS = [
  {
    id: 1,
    name: "Punjabi Tadka",
    cuisines: "North Indian, Punjabi, Tandoor",
    rating: 4.3,
    time: "28 mins",
    cost: "₹350 for two",
    offer: "50% OFF up to ₹100",
    color: "#f7b733",
    emoji: "🍛",
    menu: [
      { id: 101, name: "Butter Chicken", price: 320, veg: false, desc: "Rich tomato gravy, tandoori chicken, butter, cream", rating: 4.5 },
      { id: 102, name: "Paneer Tikka Masala", price: 260, veg: true, desc: "Grilled cottage cheese in spiced onion-tomato gravy", rating: 4.4 },
      { id: 103, name: "Dal Makhani", price: 210, veg: true, desc: "Slow-cooked black lentils, butter, cream", rating: 4.6 },
      { id: 104, name: "Tandoori Roti (2 pc)", price: 60, veg: true, desc: "Whole wheat bread from the clay oven", rating: 4.2 },
      { id: 105, name: "Chicken Biryani", price: 280, veg: false, desc: "Layered basmati rice, spiced chicken, saffron", rating: 4.5 },
      { id: 106, name: "Gulab Jamun (2 pc)", price: 90, veg: true, desc: "Milk dumplings soaked in rose-cardamom syrup", rating: 4.3 },
    ],
  },
  {
    id: 2,
    name: "Sushi Yama",
    cuisines: "Japanese, Sushi, Asian",
    rating: 4.5,
    time: "35 mins",
    cost: "₹600 for two",
    offer: "20% OFF above ₹399",
    color: "#4ecdc4",
    emoji: "🍣",
    menu: [
      { id: 201, name: "California Roll", price: 320, veg: false, desc: "Crab stick, avocado, cucumber, sesame", rating: 4.4 },
      { id: 202, name: "Veg Tempura Roll", price: 280, veg: true, desc: "Crisp vegetable tempura, spicy mayo", rating: 4.2 },
      { id: 203, name: "Salmon Nigiri (4 pc)", price: 420, veg: false, desc: "Fresh salmon over seasoned sushi rice", rating: 4.7 },
      { id: 204, name: "Miso Soup", price: 120, veg: true, desc: "Tofu, wakame, scallions, dashi broth", rating: 4.1 },
      { id: 205, name: "Chicken Katsu Curry", price: 380, veg: false, desc: "Crispy chicken cutlet, Japanese curry, rice", rating: 4.5 },
    ],
  },
  {
    id: 3,
    name: "Pizza Piazza",
    cuisines: "Italian, Pizza, Fast Food",
    rating: 4.1,
    time: "25 mins",
    cost: "₹400 for two",
    offer: "Buy 1 Get 1 Free",
    color: "#ff6b6b",
    emoji: "🍕",
    menu: [
      { id: 301, name: "Margherita Pizza", price: 249, veg: true, desc: "San Marzano tomato, mozzarella, fresh basil", rating: 4.3 },
      { id: 302, name: "Pepperoni Pizza", price: 349, veg: false, desc: "Double pepperoni, mozzarella, oregano", rating: 4.6 },
      { id: 303, name: "Garlic Bread Sticks", price: 149, veg: true, desc: "Wood-fired, herb butter, garlic, cheese dip", rating: 4.2 },
      { id: 304, name: "Farmhouse Pizza", price: 299, veg: true, desc: "Onion, capsicum, tomato, mushroom, sweetcorn", rating: 4.1 },
      { id: 305, name: "Chicken Alfredo Pasta", price: 289, veg: false, desc: "Penne, grilled chicken, creamy alfredo sauce", rating: 4.4 },
    ],
  },
  {
    id: 4,
    name: "Dragon Wok",
    cuisines: "Chinese, Asian, Noodles",
    rating: 4.0,
    time: "30 mins",
    cost: "₹300 for two",
    offer: "Free delivery",
    color: "#ee5a6f",
    emoji: "🥡",
    menu: [
      { id: 401, name: "Veg Hakka Noodles", price: 180, veg: true, desc: "Wok-tossed noodles, julienned vegetables", rating: 4.1 },
      { id: 402, name: "Chilli Chicken", price: 250, veg: false, desc: "Crispy chicken, bell peppers, sweet-spicy sauce", rating: 4.4 },
      { id: 403, name: "Veg Manchurian", price: 200, veg: true, desc: "Fried veg balls, tangy manchurian gravy", rating: 4.2 },
      { id: 404, name: "Spring Rolls (6 pc)", price: 160, veg: true, desc: "Crispy rolls, cabbage-carrot filling", rating: 4.0 },
      { id: 405, name: "Schezwan Fried Rice", price: 210, veg: true, desc: "Wok-fried rice, schezwan sauce, spring onion", rating: 4.3 },
    ],
  },
  {
    id: 5,
    name: "The Burger Lab",
    cuisines: "American, Burgers, Fast Food",
    rating: 4.4,
    time: "22 mins",
    cost: "₹280 for two",
    offer: "ITEMS AT ₹99",
    color: "#f9a826",
    emoji: "🍔",
    menu: [
      { id: 501, name: "Classic Cheese Burger", price: 179, veg: false, desc: "Beef-style patty, cheddar, lettuce, house sauce", rating: 4.5 },
      { id: 502, name: "Crispy Veg Burger", price: 149, veg: true, desc: "Potato-corn patty, mayo, lettuce, tomato", rating: 4.2 },
      { id: 503, name: "Loaded Fries", price: 139, veg: true, desc: "Fries, cheese sauce, jalapeños, herbs", rating: 4.4 },
      { id: 504, name: "Peri Peri Chicken Burger", price: 199, veg: false, desc: "Grilled chicken, peri peri mayo, slaw", rating: 4.6 },
      { id: 505, name: "Chocolate Shake", price: 129, veg: true, desc: "Thick shake, chocolate syrup, whipped cream", rating: 4.3 },
    ],
  },
  {
    id: 6,
    name: "South Spice",
    cuisines: "South Indian, Kerala, Chettinad",
    rating: 4.6,
    time: "27 mins",
    cost: "₹250 for two",
    offer: "40% OFF up to ₹80",
    color: "#6c5ce7",
    emoji: "🥥",
    menu: [
      { id: 601, name: "Masala Dosa", price: 120, veg: true, desc: "Crisp rice crepe, spiced potato filling, chutney", rating: 4.7 },
      { id: 602, name: "Idli Sambar (4 pc)", price: 90, veg: true, desc: "Steamed rice cakes, lentil sambar, coconut chutney", rating: 4.5 },
      { id: 603, name: "Kerala Parotta (2 pc)", price: 70, veg: true, desc: "Flaky layered flatbread", rating: 4.4 },
      { id: 604, name: "Chicken Chettinad", price: 260, veg: false, desc: "Fiery Chettinad spices, curry leaves, coconut", rating: 4.6 },
      { id: 605, name: "Filter Coffee", price: 50, veg: true, desc: "South Indian decoction coffee, frothed milk", rating: 4.5 },
    ],
  },
];

function getRestaurantById(id) {
  return RESTAURANTS.find((r) => r.id === Number(id));
}
